### ISSUE TITLE
it can't work if the '.heapsnapshot' file too big (my snapshot has 1.8G)

### ISSUE THREAD

**Issue by tiegangli** [hsiaosiyuan0/heapquery-js#1] opened 2021-11-23 13:40 UTC
Initializing database...
(node:26008) UnhandledPromiseRejectionWarning: Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (buffer.js:605:37)
    at Buffer.toString (buffer.js:804:14)
    at readFileHandle (internal/fs/promises.js:318:36)
    at async restoreDump (C:\Users\admin\AppData\Roaming\npm-cache\_npx\26008\node_modules\heapquery\index.js:29:15)
    at async run (C:\Users\admin\AppData\Roaming\npm-cache\_npx\26008\node_modules\heapquery\index.js:177:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
internal/fs/utils.js:314
    throw err;
    ^

Error: EPERM: operation not permitted, unlink 'C:\Users\admin\AppData\Roaming\npm-cache\_npx\26008\node_modules\heapquery\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
    at Object.unlinkSync (fs.js:1251:3)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:219:13)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:7)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:217:5)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5 {
  errno: -4048,
  syscall: 'unlink',
  code: 'EPERM',

**Comment by hsiaosiyuan0** [comment] 2021-11-23 23:12
That's true and as the error message pointed, it seems caused by the max string size hard code in nodejs internal [FYI](https://stackoverflow.com/questions/68230031/cannot-create-a-string-longer-than-0x1fffffe8-characters-in-json-parse)

It maybe resolved by replacing the `JSON.parse` usage at [index.js#L29](https://github.com/hsiaosiyuan0/heapquery-js/blob/master/index.js#L29) with other streaming parsers like [stream-json](https://www.npmjs.com/package/stream-json)

**Closed as completed by hsiaosiyuan0** 2021-11-23 23:12 UTC
